### ISSUE TITLE
Färgen saknas i ordet. Men rätt på tangentbordet

### ISSUE THREAD

**Issue by TechnoX** [eldh/ordla#2]
Hej och tack för en kul svensk variant!! 

Spoiler för dagens ord nu!

T blev inte gult uppe i ordet fastän det är med i rätt svar. Däremot blev det helt korrekt gult istället för grönt på tangentbordet. En aning förvirrande.

![Screenshot_20220121-012432](https://user-images.githubusercontent.com/1463156/150443783-63d70a51-6140-4ddf-9cf4-8e6ec34c3153.jpg)

**Comment by eldh** [comment]
Tack för buggrapporten, jag fixar!
